# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-17 00:11
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('estado', models.CharField(max_length=50)),
                ('documento', models.FileField(blank=True, upload_to='media/documentos')),
                ('observacion', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=50)),
                ('noticia', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('referencia', models.CharField(max_length=12)),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='tramites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
        migrations.AddField(
            model_name='detalle',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='web.tramite'),
        ),
    ]
