# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosotros_primero', models.CharField(max_length=400)),
                ('nosotros_segundo', models.CharField(max_length=400)),
                ('nosotros_tercero', models.CharField(max_length=400)),
            ],
        ),
    ]
