# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-17 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_noticias_activo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='noticias',
            new_name='noticia',
        ),
    ]
