# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160314_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle',
            options={'ordering': ('fecha',)},
        ),
        migrations.AlterModelOptions(
            name='tramite',
            options={'ordering': ('titulo',)},
        ),
        migrations.AlterField(
            model_name='detalle',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='web.tramite'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to=settings.AUTH_USER_MODEL),
        ),
    ]
