# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 22:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160317_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='estado',
            field=models.TextField(default=datetime.datetime(2016, 3, 17, 22, 21, 27, 119196, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
