# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_detalle_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
