# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20160317_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='documento',
            field=models.FileField(blank=True, upload_to='documentos'),
        ),
    ]
