# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20160317_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='observacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
