# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20160405_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nosotros_primero',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='nosotros_segundo',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='nosotros_tercero',
            name='autor',
        ),
        migrations.AlterField(
            model_name='tramite',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='tramites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='nosotros_primero',
        ),
        migrations.DeleteModel(
            name='nosotros_segundo',
        ),
        migrations.DeleteModel(
            name='nosotros_tercero',
        ),
    ]
